# Generated by Django 5.1.5 on 2025-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='choices',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('AR', 'Archived')], default='DF', max_length=2),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
