# Generated by Django 5.1.5 on 2025-09-23 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_created_at_blog_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, unique_for_date='publish'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-publish'], name='blog_blog_publish_1d1149_idx'),
        ),
    ]
